package yutautil;

#if macro
import haxe.macro.Context;
import haxe.macro.Expr;
#end

/**
 * Generates the AbstractData abstract type at compile time via Context.defineModule.
 * Called from TypeCollectionMacro.initializeBuildCollection early during compilation,
 * before Abstract.hx is typed.
 *
 * AbstractData is an intermediate abstract for type conversion chaining:
 *   Abstract -> AbstractData -> Dynamic -> TargetType
 *
 * AbstractData has a single @:to Dynamic method that:
 *   1. Casts the stored value to Any to promote it to its true runtime type
 *   2. Uses TypeHandler.inferValueType to determine the actual type string
 *   3. Checks canConvertTo and uses convertValueTo for proper abstract conversion
 *   4. Falls back to returning the raw value if no conversion is needed
 *
 * Since Dynamic is assignable to any type in Haxe, this enables implicit
 * conversion to all types through the chain.
 */
class AbstractConversionMacro {
	#if macro
	/**
	 * Generate and define the AbstractData module via Context.defineModule.
	 * Creates an abstract over AbstractRuntimeInfo with:
	 *   - @:from AbstractRuntimeInfo (implicit wrap)
	 *   - @:to Dynamic (extracts this.value, enabling conversion to any type)
	 *
	 * Called by TypeCollectionMacro during early initialization.
	 */
	public static function generateAbstractDataModule():Void {
		// AbstractRuntimeInfo is a sub-type defined in module yutautil.Abstract
		var underlyingTypePath:TypePath = {pack: ["yutautil"], name: "Abstract", sub: "AbstractRuntimeInfo"};

		// Single @:to Dynamic field that performs proper type-aware conversion.
		// Casts value to Any to promote it to its true runtime type, infers
		// the type name via TypeHandler, then uses convertValueTo for proper conversion.
		// Falls back to raw value if no conversion is needed or available.
		var toDynamicField:Field = {
			name: "__to_Dynamic",
			doc: "Type-aware conversion: infers runtime type, checks convertibility, and converts properly.",
			access: [APublic],
			kind: FFun({
				args: [],
				ret: TPath({pack: ([] : Array<String>), name: "Dynamic"}),
				expr: macro {
					// Promote to Any to get true runtime type info
					var anyVal:Any = this.value;
					// Infer the actual runtime type string (handles primitives, classes, structures)
					var inferredType:String = yutautil.TypeHandler.inferValueType(anyVal);
					// If the abstract can convert to the inferred type, do a proper conversion
					if (this.canConvertTo(inferredType)) {
						return this.convertValueTo(anyVal, inferredType);
					}
					// Cannot convert - throw descriptive error
					throw 'Cannot convert Abstract(' + this.name + ') to ' + inferredType;
				}
			}),
			pos: Context.currentPos(),
			meta: [{name: ":to", pos: Context.currentPos(), params: []}]
		};

		var typeDef:TypeDefinition = {
			pack: ["yutautil"],
			name: "AbstractData",
			pos: Context.currentPos(),
			kind: TDAbstract(
				TPath(underlyingTypePath),
				[TPath(underlyingTypePath)],
				([] : Array<ComplexType>)
			),
			fields: [toDynamicField],
			doc: "Auto-generated intermediate abstract for type conversion chaining.\n"
				+ "Chain: Abstract -> AbstractData -> Dynamic -> TargetType.\n"
				+ "Generated by AbstractConversionMacro via TypeCollectionMacro."
		};

		Context.defineModule("yutautil.AbstractData", [typeDef]);
		trace("AbstractConversionMacro: Defined AbstractData module with single @:to Dynamic conversion");
	}
	#end
}
